INSERT INTO `players`(`team`, `last_name`, `first_name`, `jersey_number`) VALUES 
(1,'Bardillon','Romeo Jr', 1),
(1,'Pascua','Jayp', 4),
(1,'Comia','Aldwin', 7),
(1,'Charles','Ivan', 10),
(1,'Bautista','Ivan', 26),
(1,'Beato','Ejhay', 14),
(1,'Evangelista','Cyrus Karl', 9),
(1,'Esturas','Rafael', 11),
(1,'Teraytay','Jay Lou', 13),
(1,'Ambas','Cyrus', 12),
(1,'Sagrado','Jimboy', 22),
(1,'Pili','RJ', 23),
(1,'Gomez','Gerald', 30),
(1,'San Juan','Jayjay', 44),
(1,'Rebullido','Mico', 77);

INSERT INTO `players`(`team`, `last_name`, `first_name`, `jersey_number`) VALUES 
(2,'Lualhati','Feisty_Uno',1),
(2,'Moralidad','RJ',11),
(2,'Dime','Jaypee',15),
(2,'Togonon','Joefry', 17),
(2,'Acosta','Julius', 18),
(2,'Teraytay','Julius', 20),
(2,'Espinosa','Juan Carlo',21),
(2,'Ramos','Romy',22 ),
(2,'Lualhati','Kenneth', 24),
(2,'Balong','Denver', 26),
(2,'Dime','Xaveir John', 27),
(2,'Barashari','Regieson', 28),
(2,'Consignado','Mark', 29),
(2,'Mendoza','Jay-Ar', 99);

INSERT INTO `players`(`team`, `last_name`, `first_name`, `jersey_number`) VALUES 
(3,'Sesante','Raffy',0),
(3,'Balabadan','Joehamir',1),
(3,'Beldad','Roy',5),
(3,'Dizon','Glen',6),
(3,'Monicit','Arnel',8),
(3,'Ramos','', 10),
(3,'Beldad','Robert',11),
(3,'Dumayas','Nikko',12 ),
(3,'Logo','Jaff',17),
(3,'Prejoles','', 22),
(3,'Da Silva','Rafa',23),
(3,'Molabola','Johren',26),
(3,'Perez','Gerald', 28);

INSERT INTO `players`(`team`, `last_name`, `first_name`, `jersey_number`) VALUES 
(4,'Marabe','Kurt',2),
(4,'Bebe','Jimaico',4),
(4,'Prejoles','MJ',6),
(4,'Narvaez','Yow',9),
(4,'Beldad','Rob',10),
(4,'Lucido','Jovencio', 11),
(4,'Caraig','Garrent',12),
(4,'Enseñado','Aaron',18 ),
(4,'Ceneta','Jake',19),
(4,'Erfe','Jezrel', 22),
(4,'Mago','Bradly',28),
(4,'Bebe','',34),
(4,'Magpantay','Alfredo', 99);